icons = {
    "comfyrock/Upscale": "🧩 comfyrock Studio/✨ Essential/🔍 Upscale",
    "comfyrock/Model Merge": "🧩 comfyrock Studio/✨ Essential/⛏️ Model Merge",
    "comfyrock/Utils/Logic": "🧩 comfyrock Studio/🛠️ Utils/🔀 Logic",
    "comfyrock/Utils/Conditional": "🧩 comfyrock Studio/🛠️ Utils/🔀 Conditional", 
    "comfyrock/Utils/Process": "🧩 comfyrock Studio/🛠️ Utils/🔂 Process",
    "comfyrock/Utils/Index": "🧩 comfyrock Studio/🛠️ Utils/🔢 Index",
    "comfyrock/Utils/Conversion": "🧩 comfyrock Studio/🛠️ Utils/🔧 Conversion",
    "comfyrock/Utils/Random": "🧩 comfyrock Studio/🛠️ Utils/🎲 Random",
    "comfyrock/Utils/Text": "🧩 comfyrock Studio/🛠️ Utils/🔤 Text",    
    "comfyrock/Utils/Other": "🧩 comfyrock Studio/🛠️ Utils/⚙️ Other",
    "comfyrock/LoRA": "🧩 comfyrock Studio/✨ Essential/💊 LoRA",
    "comfyrock/ControlNet": "🧩 comfyrock Studio/✨ Essential/🕹️ ControlNet",
    "comfyrock/XY Grid": "🧩 comfyrock Studio/✨ Essential/📉 XY Grid",
    "comfyrock/SDXL": "🧩 comfyrock Studio/✨ Essential/🌟 SDXL",
    "comfyrock/List": "🧩 comfyrock Studio/✨ Essential/📜 List",
    "comfyrock/List/IO": "🧩 comfyrock Studio/✨ Essential/📜 List/⌨️ IO",    
    "comfyrock/List/Utils": "🧩 comfyrock Studio/✨ Essential/📜 List/🛠️ Utils",      
    "comfyrock/Aspect Ratio": "🧩 comfyrock Studio/✨ Essential/🔳 Aspect Ratio",
    "comfyrock/Pipe/Module": "🧩 comfyrock Studio/✨ Essential/🎷 Pipe/✈️ Module",
    "comfyrock/Pipe/Image": "🧩 comfyrock Studio/✨ Essential/🎷 Pipe/🛩️ Image",
    "comfyrock/Pipe/Bus": "🧩 comfyrock Studio/✨ Essential/🎷 Pipe/🚌 Bus",    
    "comfyrock/Pipe": "🧩 comfyrock Studio/✨ Essential/🎷 Pipe",
    "comfyrock/Graphics/Text": "🧩 comfyrock Studio/👾 Graphics/🔤 Text",
    "comfyrock/Graphics/Layout": "🧩 comfyrock Studio/👾 Graphics/🌁 Layout",
    "comfyrock/Graphics/Template": "🧩 comfyrock Studio/👾 Graphics/📱 Template",
    "comfyrock/Graphics/Filter": "🧩 comfyrock Studio/👾 Graphics/🎨 Filter",
    "comfyrock/Graphics/Pattern": "🧩 comfyrock Studio/👾 Graphics/🌈 Pattern",
    "comfyrock/Graphics/Shape": "🧩 comfyrock Studio/👾 Graphics/🟣 Shape",
    "comfyrock/Graphics/3D": "🧩 comfyrock Studio/👾 Graphics/3D",
    "comfyrock/Graphics/Utilty": "🧩 comfyrock Studio/👾 Graphics/🔧 Utility",
    "comfyrock/Workflow": "🧩 comfyrock Studio/✨ Essential/Workflow",     
    "comfyrock/Essential/Core": "🧩 comfyrock Studio/✨ Essential/📦 Core",
    "comfyrock/Essential/Legacy": "🧩 comfyrock Studio/✨ Essential/💀 Legacy",
    "comfyrock/Animation/Camera": "🧩 comfyrock Studio/🎥 Animation/🎦 Camera",
    "comfyrock/Animation/Utils": "🧩 comfyrock Studio/🎥 Animation/🛠️ Utils",
    "comfyrock/Animation/Schedule": "🧩 comfyrock Studio/🎥 Animation/📋 Schedule",
    "comfyrock/Animation/Schedulers": "🧩 comfyrock Studio/🎥 Animation/📑 Schedulers",
    "comfyrock/Animation/Prompt": "🧩 comfyrock Studio/🎥 Animation/📝 Prompt",
    "comfyrock/Animation/Legacy": "🧩 comfyrock Studio/🎥 Animation/💀 Legacy",
    "comfyrock/Animation/Interpolate": "🧩 comfyrock Studio/🎥 Animation/🔢 Interpolate",
    "comfyrock/Animation/IO": "🧩 comfyrock Studio/🎥 Animation/⌨️ IO",
}
